#logging
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: mattrank
    password: 5minrspp
  application:
    name: demo1
  data:
    mongodb:
      host: localhost
      port: 27017
      database: SSSS
  profiles:
    active: dev

rabbit:
  queue: matts_new_queue

server:
  port: 7885

logging:
  level:
    org:
      springframework: debug
  file:
    name: ${java.io.tmpdir}/${spring.application.name}.log
